/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_leshan_client_demo_MyHumidity */

#ifndef _Included_org_eclipse_leshan_client_demo_MyDHT11
#define _Included_org_eclipse_leshan_client_demo_MyDHT11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_leshan_client_demo_MyDHT11
 * Method:    readData
 * Signature: (I)[F
 */
package org.eclipse.kura.DHT11
JNIEXPORT jfloatArray JNICALL Java_org_eclipse_kura_DHT11_MyDHT11_readData
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
